### ISSUE TITLE
Steemconnect login not working

### ISSUE THREAD

**Issue by alixanc** [wehmoen/2exy.com#1]
Whenever I try to login the d.tube account via steemconnect, it's first explains the rights and gives me a login, but when I enter my data and click enter, I'm stuck with a long loading circle resulting in a 404. Happens on macOS Sierra with Firefox, Chrome and Safari as well as on a Chromebook.

**Comment by wehmoen** [comment]
![image](https://user-images.githubusercontent.com/6608103/35315737-50035300-00ce-11e8-9338-cf501c5fc76c.png)
Can't reproduce. SteemConnect login works fine for me

**Comment by alixanc** [comment]
Update: I just got another steem account and tried to log in in with that one and it works perfectly fine, so it seems to be related to my other channel and/or steemconnect. Thanks for your efforts, hopefully I'll work out how to get the other account working ;)
